# Generated by Django 3.0.2 on 2020-01-22 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pic_folder/')),
                ('in_stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_goods', models.PositiveIntegerField()),
                ('time_of_purchase', models.DateTimeField(default=django.utils.timezone.now)),
                ('info_about_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('info_about_good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_return', models.DateTimeField(default=django.utils.timezone.now)),
                ('info_about_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Purchase')),
            ],
        ),
    ]
