# Generated by Django 3.0.2 on 2020-01-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity_of_goods',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
