# Generated by Django 3.0.2 on 2020-01-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200122_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_of_goods',
            field=models.PositiveIntegerField(),
        ),
    ]
