# Generated by Django 3.0.2 on 2020-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200123_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
